/**
 * Backend Project Generator
 * Takes entities, endpoints, and API routes from the generation engine and
 * produces a complete, ready-to-run backend project scaffold:
 * package.json, tsconfig.json, server entry, middleware, config, and README.
 */

import type { GeneratedEntity, GeneratedEndpoint } from "./generate";

// ── Types ──────────────────────────────────────────────────────────────────

export interface BackendProject {
  packageJson: string;
  tsconfigJson: string;
  indexTs: string;
  middleware: { filename: string; content: string }[];
  configTs: string;
  envExample: string;
  readme: string;
}

// ── Helpers ────────────────────────────────────────────────────────────────

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function pascalToWords(name: string): string {
  return name.replace(/([A-Z])/g, " $1").trim();
}

// ── Main generator ─────────────────────────────────────────────────────────

export function generateBackendProject(
  entities: GeneratedEntity[],
  endpoints: GeneratedEndpoint[],
  apiRoutes: string
): BackendProject {
  const projectSlug =
    entities.length > 0
      ? entities
          .map((e) => e.name.toLowerCase())
          .join("-")
          .slice(0, 60) + "-api"
      : "app-api";
  const projectTitle =
    entities.length > 0
      ? entities
          .map((e) => pascalToWords(e.name))
          .join(" • ") + " API"
      : "Application API";

  // ── package.json ──────────────────────────────────────────────────────
  const packageJson = JSON.stringify(
    {
      name: projectSlug,
      version: "1.0.0",
      description: `Generated ${projectTitle} — Autonomous Software Generation Platform`,
      type: "module",
      scripts: {
        dev: "bun run --watch src/index.ts",
        build: "bun build src/index.ts --outdir=dist --target=bun",
        start: "bun run dist/index.js",
        "db:migrate": "bun run src/db/migrate.ts",
        "db:seed": "bun run src/db/seed.ts",
      },
      dependencies: {
        hono: "^4.6.0",
        zod: "^3.23.0",
        "@hono/zod-validator": "^0.4.0",
        postgres: "^3.4.0",
        dotenv: "^16.4.0",
      },
      devDependencies: {
        typescript: "^5.6.0",
        "@types/node": "^22.0.0",
        "bun-types": "latest",
      },
    },
    null,
    2
  );

  // ── tsconfig.json ─────────────────────────────────────────────────────
  const tsconfigJson = JSON.stringify(
    {
      compilerOptions: {
        target: "ESNext",
        module: "ESNext",
        moduleResolution: "bundler",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        jsx: "react-jsx",
        lib: ["ESNext"],
        types: ["bun-types"],
        baseUrl: ".",
        paths: {
          "~/*": ["./src/*"],
        },
      },
      include: ["src/**/*.ts"],
      exclude: ["node_modules", "dist"],
    },
    null,
    2
  );

  // ── src/config.ts ─────────────────────────────────────────────────────
  const configTs = `/**
 * Environment Configuration
 * Generated by Genesis Platform ASGP Engine
 *
 * Loads and validates environment variables using dotenv.
 * All config values are typed and have sensible defaults for development.
 */

import { config } from "dotenv";

// Load .env file (no-op in production when env vars are set externally)
config();

export interface AppConfig {
  port: number;
  databaseUrl: string;
  nodeEnv: "development" | "production" | "test";
  corsOrigin: string;
  logLevel: "debug" | "info" | "warn" | "error";
}

function requireEnv(key: string, fallback?: string): string {
  const value = process.env[key] ?? fallback;
  if (value === undefined) {
    throw new Error(\`Missing required environment variable: \${key}\`);
  }
  return value;
}

export const appConfig: AppConfig = {
  port: parseInt(process.env.PORT ?? "3001", 10),
  databaseUrl: requireEnv(
    "DATABASE_URL",
    "postgresql://app_user:app_password@localhost:5432/${projectSlug.replace(/-api$/, "-db")}"
  ),
  nodeEnv: (process.env.NODE_ENV as AppConfig["nodeEnv"]) ?? "development",
  corsOrigin: process.env.CORS_ORIGIN ?? "*",
  logLevel: (process.env.LOG_LEVEL as AppConfig["logLevel"]) ?? "info",
};

export default appConfig;
`;

  // ── Middleware files ───────────────────────────────────────────────────
  const errorHandler = `/**
 * Error Handler Middleware
 * Generated by Genesis Platform ASGP Engine
 *
 * Catches all unhandled errors and returns a structured JSON response.
 */

import type { Context } from "hono";
import type { StatusCode } from "hono/utils/http-status";

export interface AppError extends Error {
  statusCode?: number;
  code?: string;
  details?: unknown;
}

export function errorHandler(err: AppError, c: Context) {
  const statusCode = (err.statusCode ?? 500) as StatusCode;
  const isDev = process.env.NODE_ENV === "development";

  console.error(\`[error] \${err.message}\`, isDev ? err.stack : "");

  return c.json(
    {
      error: {
        message: err.message || "Internal Server Error",
        code: err.code ?? "INTERNAL_ERROR",
        ...(isDev && { stack: err.stack }),
        ...(err.details && { details: err.details }),
      },
    },
    statusCode
  );
}
`;

  const requestLogger = `/**
 * Request Logger Middleware
 * Generated by Genesis Platform ASGP Engine
 *
 * Logs each incoming request with method, path, status, and duration.
 */

import type { Context, Next } from "hono";

export async function requestLogger(c: Context, next: Next) {
  const start = Date.now();
  const method = c.req.method;
  const path = c.req.path;

  await next();

  const duration = Date.now() - start;
  const status = c.res.status;

  const color = status >= 500 ? "\\x1b[31m" : status >= 400 ? "\\x1b[33m" : "\\x1b[32m";
  console.log(
    \`\\x1b[90m[\${new Date().toISOString()}]\\x1b[0m \${color}\${method}\\x1b[0m \${path} \\x1b[90m→\\x1b[0m \${status} \\x1b[90m(\${duration}ms)\\x1b[0m\`
  );
}
`;

  const authStub = `/**
 * Authentication Middleware (Stub)
 * Generated by Genesis Platform ASGP Engine
 *
 * Replace with your actual authentication logic (JWT, session, OAuth, etc.).
 * This stub simply extracts a Bearer token and attaches a mock user context.
 */

import type { Context, Next } from "hono";

export interface AuthUser {
  id: string;
  email: string;
  role: "admin" | "user";
}

// Extend Hono's ContextVariableMap for type-safe context access
declare module "hono" {
  interface ContextVariableMap {
    user: AuthUser;
  }
}

export async function authMiddleware(c: Context, next: Next) {
  const authHeader = c.req.header("Authorization");

  if (authHeader?.startsWith("Bearer ")) {
    const token = authHeader.slice(7);

    // TODO: Verify JWT or session token here
    // For now, set a mock user for development
    c.set("user", {
      id: "00000000-0000-0000-0000-000000000001",
      email: "dev@example.com",
      role: "admin",
    });
  } else {
    // Set anonymous user — individual routes can enforce auth as needed
    c.set("user", {
      id: "anonymous",
      email: "",
      role: "user",
    });
  }

  await next();
}

/**
 * Require authentication — use as route middleware to protect endpoints.
 *
 * Usage:
 *   router.get("/admin", requireAuth, (c) => { ... })
 */
export async function requireAuth(c: Context, next: Next) {
  const user = c.get("user");
  if (!user || user.id === "anonymous") {
    return c.json({ error: { message: "Authentication required", code: "UNAUTHORIZED" } }, 401);
  }
  await next();
}
`;

  const middleware: { filename: string; content: string }[] = [
    { filename: "error-handler.ts", content: errorHandler },
    { filename: "request-logger.ts", content: requestLogger },
    { filename: "auth.ts", content: authStub },
  ];

  // ── src/index.ts ───────────────────────────────────────────────────────
  const entityList = entities.map((e) => e.name).join(", ");
  const domains = new Set<string>();
  for (const ep of endpoints) {
    const path = ep.path.replace(/^\/api\//, "").split("/")[0];
    if (path) domains.add(path);
  }
  const domainList = [...domains].join(", ");

  const indexTs = `/**
 * ${projectTitle}
 * Generated by Genesis Platform ASGP Engine
 *
 * Entities: ${entityList || "Custom"}
 * API Domains: ${domainList || "root"}
 *
 * Framework: Hono (Bun)
 * Port: 3001
 */

import { Hono } from "hono";
import { cors } from "hono/cors";
import { logger } from "hono/logger";
import apiRouter from "./routes";
import { errorHandler } from "./middleware/error-handler";
import { requestLogger } from "./middleware/request-logger";
import { authMiddleware } from "./middleware/auth";
import appConfig from "./config";

// ── Initialize app ────────────────────────────────────────────────────────

const app = new Hono();

// ── Global middleware ─────────────────────────────────────────────────────

// CORS — permissive in development, restrict in production
app.use(
  "*",
  cors({
    origin: appConfig.corsOrigin,
    allowMethods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    allowHeaders: ["Content-Type", "Authorization", "X-Requested-With"],
    exposeHeaders: ["Content-Length", "X-Request-Id"],
    maxAge: 86400,
    credentials: true,
  })
);

// Request logging
app.use("*", requestLogger);

// Structured logging (Hono built-in)
if (appConfig.nodeEnv === "development") {
  app.use("*", logger());
}

// Authentication (sets context; individual routes enforce as needed)
app.use("*", authMiddleware);

// ── Routes ────────────────────────────────────────────────────────────────

// Health check
app.get("/health", (c) => {
  return c.json({
    status: "ok",
    service: "${projectSlug}",
    version: "1.0.0",
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
  });
});

// Mount generated API routes under /api
app.route("/api", apiRouter);

// 404 handler
app.notFound((c) => {
  return c.json(
    {
      error: {
        message: "Not Found",
        code: "NOT_FOUND",
        path: c.req.path,
      },
    },
    404
  );
});

// Error handler — must be registered last
app.onError(errorHandler);

// ── Start server ──────────────────────────────────────────────────────────

const server = Bun.serve({
  port: appConfig.port,
  hostname: "0.0.0.0",
  fetch: app.fetch,
});

console.log(
  \`\\n🚀 \${"${projectSlug}"} running at \\x1b[36mhttp://localhost:\${server.port}\\x1b[0m\`
);
console.log(\`   Environment: \\x1b[33m\${appConfig.nodeEnv}\\x1b[0m\`);
console.log(\`   Health:      http://localhost:\${server.port}/health\`);
console.log(\`   API:         http://localhost:\${server.port}/api\`);
console.log();

// ── Graceful shutdown ──────────────────────────────────────────────────────

let shuttingDown = false;

async function shutdown(signal: string) {
  if (shuttingDown) return;
  shuttingDown = true;

  console.log(\`\\n\\x1b[33m[\${signal}] Shutting down gracefully...\\x1b[0m\`);

  // Close the Bun server — stops accepting new connections
  server.stop();

  // Give in-flight requests time to complete
  await new Promise((resolve) => setTimeout(resolve, 1000));

  console.log("\\x1b[32m✓ Server stopped\\x1b[0m");
  process.exit(0);
}

process.on("SIGTERM", () => shutdown("SIGTERM"));
process.on("SIGINT", () => shutdown("SIGINT"));

export default app;
`;

  // ── .env.example ──────────────────────────────────────────────────────
  const envExample = `# ${projectTitle}
# Generated by Genesis Platform ASGP Engine
#
# Copy to .env and update for your environment.

PORT=3001
DATABASE_URL=postgresql://app_user:app_password@localhost:5432/${projectSlug.replace(/-api$/, "-db")}

# CORS — set to your frontend origin in production
CORS_ORIGIN=*

# Environment
NODE_ENV=development

# Logging: debug | info | warn | error
LOG_LEVEL=info
`;

  // ── README.md ─────────────────────────────────────────────────────────
  const readme = `# ${projectTitle}

> Generated by [Genesis Platform ASGP Engine](https://genesis-platform.ai)

A production-ready ${entities.length > 0 ? entities.map(e => e.name).join(" • ") : "REST"} backend API built with **Hono** + **Bun** + **PostgreSQL**.

## Quick Start

\`\`\`bash
# 1. Install dependencies
bun install

# 2. Set up environment
cp .env.example .env

# 3. Start database (requires Docker)
docker compose up -d

# 4. Run migrations
bun run db:migrate

# 5. Seed sample data
bun run db:seed

# 6. Start development server
bun run dev
\`\`\`

The API will be available at **http://localhost:3001**.

## API Endpoints

${endpoints.map(ep => `- **${ep.method}** \`${ep.path}\` — ${ep.description}`).join("\n")}

## Project Structure

\`\`\`
├── src/
│   ├── index.ts           # Server entry point
│   ├── config.ts          # Environment configuration
│   ├── routes.ts          # Generated API routes (${endpoints.length} endpoints)
│   ├── middleware/
│   │   ├── error-handler.ts   # Global error handling
│   │   ├── request-logger.ts  # HTTP request logging
│   │   └── auth.ts            # Authentication middleware
│   └── db/
│       ├── connection.ts      # Database connection pool
│       ├── migrate.ts         # Migration runner
│       └── seed.ts            # Seed data script
├── migrations/
│   ├── 001_create_tables.sql
│   └── 002_add_indexes.sql
├── docker-compose.yml         # PostgreSQL 16
├── package.json
├── tsconfig.json
├── .env.example
└── README.md
\`\`\`

${entities.length > 0 ? `## Data Model

${entities.map(e => {
  return `### ${e.name}
${e.fields.map(f => `- \`${f.name}\` — \`${f.type}\`${f.required ? " (required)" : ""}${f.description ? ` — ${f.description}` : ""}`).join("\n")}`;
}).join("\n\n")}
` : ""}
## Scripts

| Script | Description |
|--------|-------------|
| \`bun run dev\` | Start dev server with hot reload |
| \`bun run build\` | Build for production |
| \`bun run start\` | Start production server |
| \`bun run db:migrate\` | Run database migrations |
| \`bun run db:seed\` | Insert sample data |

## Tech Stack

- **Runtime:** [Bun](https://bun.sh)
- **Framework:** [Hono](https://hono.dev)
- **Validation:** [Zod](https://zod.dev)
- **Database:** PostgreSQL 16 via [postgres.js](https://github.com/porsager/postgres)
- **Language:** TypeScript (strict mode)
`;

  return {
    packageJson,
    tsconfigJson,
    indexTs,
    middleware,
    configTs,
    envExample,
    readme,
  };
}
