/**
 * Database Project Generator
 * Takes the SQL DDL from the generation engine and produces a complete,
 * ready-to-run database project: migrations, Docker Compose, connection
 * module, seed data script, migration runner, and env template.
 */

import type { GeneratedEntity, Relationship, DatabaseProject } from "./generate";

// ── Topological Sort for FK-safe insertion order ──────────────────────────

function topologicalSort(
  entities: GeneratedEntity[],
  relationships: Relationship[]
): GeneratedEntity[] {
  const nameSet = new Set(entities.map((e) => e.name));
  const inDegree = new Map<string, number>();
  const adj = new Map<string, string[]>();

  for (const e of entities) {
    inDegree.set(e.name, 0);
    adj.set(e.name, []);
  }

  for (const rel of relationships) {
    if (rel.type === "one-to-many") {
      if (nameSet.has(rel.from) && nameSet.has(rel.to)) {
        adj.get(rel.from)!.push(rel.to);
        inDegree.set(rel.to, (inDegree.get(rel.to) || 0) + 1);
      }
    }
  }

  const queue: string[] = [];
  for (const [name, deg] of inDegree) {
    if (deg === 0) queue.push(name);
  }

  const sorted: string[] = [];
  while (queue.length > 0) {
    const node = queue.shift()!;
    sorted.push(node);
    for (const neighbor of adj.get(node) || []) {
      const newDeg = (inDegree.get(neighbor) || 1) - 1;
      inDegree.set(neighbor, newDeg);
      if (newDeg === 0) queue.push(neighbor);
    }
  }

  for (const e of entities) {
    if (!sorted.includes(e.name)) sorted.push(e.name);
  }

  const entityMap = new Map(entities.map((e) => [e.name, e]));
  return sorted.map((n) => entityMap.get(n)!).filter(Boolean);
}

// ── Main generator ────────────────────────────────────────────────────────

export function generateDatabaseProject(
  entities: GeneratedEntity[],
  relationships: Relationship[],
  sql: string
): DatabaseProject {
  const projectName =
    entities.length > 0
      ? entities.map((e) => e.name.toLowerCase()).join("-") + "-db"
      : "app-db";
  const dbName = projectName.replace(/-/g, "_");

  const sortedEntities = topologicalSort(entities, relationships);

  // ── 1. Migration files ────────────────────────────────────────────────
  const migrations: { filename: string; content: string }[] = [];

  migrations.push({
    filename: "001_create_tables.sql",
    content: `-- Migration 001: Create Tables
-- Generated by Genesis Platform ASGP Engine

BEGIN;

${sql}

COMMIT;
`,
  });

  // 002: Add indexes for FK columns and commonly queried columns
  const indexLines: string[] = [];
  const indexedCols = new Set<string>();

  for (const rel of relationships) {
    if (rel.type === "one-to-many") {
      const childTable = rel.to.toLowerCase();
      const fkCol = rel.foreignKey;
      const idxKey = `${childTable}.${fkCol}`;
      if (!indexedCols.has(idxKey)) {
        indexedCols.add(idxKey);
        indexLines.push(
          `CREATE INDEX idx_${childTable}_${fkCol} ON ${childTable}(${fkCol});`
        );
      }
    } else if (rel.type === "many-to-many" && rel.junctionTable) {
      const jt = rel.junctionTable.toLowerCase();
      const fkParts = rel.foreignKey.split(",");
      for (const fk of fkParts) {
        const trimmed = fk.trim();
        const idxKey = `${jt}.${trimmed}`;
        if (!indexedCols.has(idxKey)) {
          indexedCols.add(idxKey);
          indexLines.push(
            `CREATE INDEX idx_${jt}_${trimmed} ON ${jt}(${trimmed});`
          );
        }
      }
    }
  }

  for (const entity of entities) {
    const table = entity.name.toLowerCase();
    for (const field of entity.fields) {
      const fn = field.name.toLowerCase();
      if (["status", "email", "created_at", "createdat", "type"].includes(fn)) {
        const idxKey = `${table}.${field.name}`;
        if (!indexedCols.has(idxKey)) {
          indexedCols.add(idxKey);
          indexLines.push(
            `CREATE INDEX idx_${table}_${field.name} ON ${table}(${field.name});`
          );
        }
      }
    }
  }

  if (indexLines.length > 0) {
    migrations.push({
      filename: "002_add_indexes.sql",
      content: `-- Migration 002: Add Indexes
-- Generated by Genesis Platform ASGP Engine

BEGIN;

${indexLines.join("\n")}

COMMIT;
`,
    });
  }

  // ── 2. Docker Compose ─────────────────────────────────────────────────
  const dockerCompose = `# Docker Compose — ${projectName}
# Generated by Genesis Platform ASGP Engine

version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: ${projectName}
    restart: unless-stopped
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: ${dbName}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d ${dbName}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
    driver: local
`;

  // ── 3. Connection module ──────────────────────────────────────────────
  const connectionCode = `/**
 * Database Connection Module
 * Generated by Genesis Platform ASGP Engine
 *
 * Uses the 'postgres' npm package for connection pooling.
 * Install: bun add postgres
 */

import postgres from "postgres";

const DATABASE_URL =
  process.env.DATABASE_URL ??
  "postgresql://app_user:app_password@localhost:5432/${dbName}";

const sql = postgres(DATABASE_URL, {
  max: 20,
  idle_timeout: 30,
  connect_timeout: 10,
  prepare: false,
  debug:
    process.env.NODE_ENV === "development"
      ? (conn, query, params) => {
          console.debug("[db]", query, params);
        }
      : false,
});

export async function closeConnection(): Promise<void> {
  await sql.end();
  console.log("[db] Connection pool closed");
}

process.on("SIGTERM", async () => {
  console.log("[db] SIGTERM received, closing pool...");
  await closeConnection();
  process.exit(0);
});

process.on("SIGINT", async () => {
  console.log("[db] SIGINT received, closing pool...");
  await closeConnection();
  process.exit(0);
});

export default sql;
`;

  // ── 4. Seed data script ───────────────────────────────────────────────
  const seedCode = generateSeedScript(sortedEntities, relationships, dbName);

  // ── 5. Migration runner ───────────────────────────────────────────────
  const migrateCode = `/**
 * Migration Runner
 * Generated by Genesis Platform ASGP Engine
 *
 * Reads and executes SQL migration files in order.
 * Run with: bun run src/db/migrate.ts
 */

import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import postgres from "postgres";

const DATABASE_URL =
  process.env.DATABASE_URL ??
  "postgresql://app_user:app_password@localhost:5432/${dbName}";

const MIGRATIONS_DIR = join(import.meta.dir, "..", "..", "migrations");

async function migrate() {
  const sql = postgres(DATABASE_URL, { max: 1 });

  try {
    await sql\`
      CREATE TABLE IF NOT EXISTS _migrations (
        id SERIAL PRIMARY KEY,
        filename VARCHAR(255) NOT NULL UNIQUE,
        executed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    \`;

    const executed = await sql\`SELECT filename FROM _migrations ORDER BY id\`;
    const executedSet = new Set(executed.map((r: any) => r.filename));

    const files = (await readdir(MIGRATIONS_DIR))
      .filter((f) => f.endsWith(".sql"))
      .sort();

    let ranCount = 0;
    for (const file of files) {
      if (executedSet.has(file)) {
        console.log(\`[migrate] Skipping (already run): \${file}\`);
        continue;
      }

      const content = await readFile(join(MIGRATIONS_DIR, file), "utf-8");
      console.log(\`[migrate] Running: \${file}\`);

      await sql.unsafe(content);
      await sql\`INSERT INTO _migrations (filename) VALUES (\${file})\`;

      console.log(\`[migrate] ✓ Completed: \${file}\`);
      ranCount++;
    }

    if (ranCount === 0) {
      console.log("[migrate] Already up to date.");
    } else {
      console.log(\`[migrate] ✅ Ran \${ranCount} migration(s).\`);
    }
  } catch (error) {
    console.error("[migrate] Migration failed:", error);
    process.exit(1);
  } finally {
    await sql.end();
  }
}

migrate();
`;

  // ── 6. .env.example ───────────────────────────────────────────────────
  const envExample = `# Database — ${projectName}
# Generated by Genesis Platform ASGP Engine
#
# Copy to .env and update for your environment.

DATABASE_URL=postgresql://app_user:app_password@localhost:5432/${dbName}

# Connection pool
DB_POOL_MAX=20
DB_POOL_IDLE_TIMEOUT=30

# Set to "development" to enable query debugging
NODE_ENV=development
`;

  return {
    migrations,
    dockerCompose,
    connectionCode,
    seedCode,
    migrateCode,
    envExample,
  };
}

// ── Seed data script generator ───────────────────────────────────────────

const FIRST_NAMES = [
  "Alice", "Bob", "Charlie", "Diana", "Edward", "Fiona", "George", "Hannah",
  "Ivan", "Julia", "Kevin", "Laura", "Michael", "Natalie", "Oliver", "Patricia",
];
const LAST_NAMES = [
  "Anderson", "Brown", "Clark", "Davis", "Evans", "Foster", "Garcia", "Harris",
  "Irwin", "Johnson", "Kim", "Lee", "Martinez", "Nelson", "Patel", "Quinn",
];
const DOMAINS = ["example.com", "company.org", "business.io", "mail.com"];
const STATUSES = ["active", "inactive", "pending", "draft"];
const CITIES = ["New York", "London", "Tokyo", "Paris", "Berlin", "Sydney"];

function pick<T>(arr: T[], i: number): T {
  return arr[i % arr.length];
}

function generateFieldValue(
  field: { name: string; type: string },
  entityIdx: number,
  rowIdx: number
): string {
  const ft = field.type.toLowerCase().trim();
  const fn = field.name.toLowerCase();
  const seed = entityIdx * 10 + rowIdx;

  if (fn === "id") {
    const hex = (entityIdx * 100 + rowIdx).toString(16).padStart(8, "0");
    return `'00000000-0000-0000-0000-${hex}'`;
  }

  if (fn === "firstname" || fn === "first_name") return `'${pick(FIRST_NAMES, rowIdx)}'`;
  if (fn === "lastname" || fn === "last_name") return `'${pick(LAST_NAMES, rowIdx)}'`;
  if (fn === "name" || fn === "title") return `'Item ${rowIdx + 1}'`;
  if (fn.includes("email")) {
    const f = pick(FIRST_NAMES, rowIdx).toLowerCase();
    const l = pick(LAST_NAMES, rowIdx).toLowerCase();
    return `'${f}.${l}@${pick(DOMAINS, seed)}'`;
  }
  if (fn === "phone" || fn.includes("phone")) return `'+1-555-${String(rowIdx + 1).padStart(4, "0")}'`;
  if (fn === "roomnumber" || fn === "room_number") return `'${100 + rowIdx}'`;
  if (fn === "trackingnumber" || fn === "tracking_number") return `'TRK-${String(rowIdx + 1).padStart(6, "0")}'`;

  if (ft === "date") {
    const d = new Date(Date.now() - (seed % 365) * 86400000);
    return `'${d.toISOString().split("T")[0]}'`;
  }
  if (ft === "datetime" || ft === "timestamp" || ft === "timestamptz") {
    const d = new Date(Date.now() - (seed % 180) * 86400000);
    return `'${d.toISOString()}'`;
  }

  if (ft === "integer" || ft === "int") return String((seed % 500) + 1);
  if (ft === "decimal" || ft === "float" || ft === "double") return (9.99 + (seed % 990)).toFixed(2);
  if (ft === "boolean" || ft === "bool") return seed % 2 === 0 ? "true" : "false";

  if (ft === "enum" || ft.startsWith("enum") || fn === "status" || fn === "type" || fn === "stage" || fn === "category" || fn === "tasktype" || fn === "task_type" || fn === "priority" || fn === "paymentstatus" || fn === "payment_status" || fn === "billingcycle" || fn === "billing_cycle") {
    // Try to use description-based enum values from statuses array
    return `'${pick(STATUSES, seed % STATUSES.length)}'`;
  }

  if (ft === "string[]" || ft.includes("[]")) {
    return `ARRAY['tag-${seed % 3 + 1}', 'tag-${(seed + 1) % 3 + 1}']`;
  }

  if (ft === "json" || ft === "jsonb") return `'{"seed": ${seed}}'`;
  if (ft === "text") return `'Sample description for row ${rowIdx + 1}.'`;

  return `'Sample ${field.name} ${rowIdx + 1}'`;
}

function generateSeedScript(
  sortedEntities: GeneratedEntity[],
  relationships: Relationship[],
  dbName: string
): string {
  const lines: string[] = [
    `/**`,
    ` * Seed Data Script`,
    ` * Generated by Genesis Platform ASGP Engine`,
    ` *`,
    ` * Inserts realistic sample data in FK-safe order.`,
    ` * Run with: bun run src/db/seed.ts`,
    ` */`,
    ``,
    `import postgres from "postgres";`,
    ``,
    `const DATABASE_URL =`,
    `  process.env.DATABASE_URL ??`,
    `  "postgresql://app_user:app_password@localhost:5432/${dbName}";`,
    ``,
    `async function seed() {`,
    `  const sql = postgres(DATABASE_URL, { max: 1 });`,
    ``,
    `  console.log("[seed] Starting seed data insertion...");`,
    `  console.log("[seed] Insertion order respects foreign key dependencies.");`,
    ``,
  ];

  // Track which entity is at which position in the sorted list
  const entityOrder = new Map<string, number>();
  sortedEntities.forEach((e, i) => entityOrder.set(e.name, i));

  for (const entity of sortedEntities) {
    const table = entity.name.toLowerCase();
    const entityIdx = entityOrder.get(entity.name) ?? 0;

    // Filter out timestamp fields that are auto-generated
    const nonGeneratedFields = entity.fields.filter(
      (f) =>
        f.name !== "created_at" &&
        f.name !== "createdAt" &&
        f.name !== "updated_at" &&
        f.name !== "updatedAt"
    );
    const columnNames = nonGeneratedFields.map((f) => f.name);

    // Determine row count
    const rowCount = entityIdx === 0 ? 3 : Math.min(4, 2 + entityIdx);

    lines.push(`  // ── ${entity.name} (${rowCount} rows) ──`);
    lines.push(`  console.log("[seed] Seeding ${table}...");`);

    // Find FK fields — need runtime ID lookups from parent tables
    const fkFields = nonGeneratedFields.filter((f) => {
      const t = f.type.toLowerCase().trim();
      const n = f.name.toLowerCase();
      return /^uuid\s*→/.test(t) || (n.endsWith("id") && n !== "id");
    });

    if (fkFields.length > 0) {
      lines.push(`  // Fetch FK references from parent tables`);
      for (const fk of fkFields) {
        const typeMatch = fk.type.match(/UUID\s*→\s*(\w[\w\s]*\w)/i);
        let parentTable = "";
        if (typeMatch) {
          parentTable = typeMatch[1].trim().toLowerCase();
        } else {
          parentTable = fk.name
            .replace(/_id$/i, "")
            .replace(/Id$/i, "")
            .toLowerCase();
        }
        lines.push(
          `  const ${parentTable}Ids = (await sql\`SELECT id FROM ${parentTable} ORDER BY created_at LIMIT ${rowCount}\`).map((r: any) => r.id);`
        );
      }
      lines.push(``);
    }

    for (let rowIdx = 0; rowIdx < rowCount; rowIdx++) {
      const values = nonGeneratedFields.map((f) => {
        const t = f.type.toLowerCase().trim();
        const n = f.name.toLowerCase();

        // FK fields: use runtime parent IDs
        if (/^uuid\s*→/.test(t) || (n.endsWith("id") && n !== "id")) {
          const typeMatch = f.type.match(/UUID\s*→\s*(\w[\w\s]*\w)/i);
          let parentTable = "";
          if (typeMatch) {
            parentTable = typeMatch[1].trim().toLowerCase();
          } else {
            parentTable = n.replace(/_id$/i, "").replace(/Id$/i, "").toLowerCase();
          }
          return `\${${parentTable}Ids[${rowIdx} % ${parentTable}Ids.length] || null}`;
        }
        return generateFieldValue(f, entityIdx, rowIdx);
      });

      lines.push(`  await sql\``);
      lines.push(
        `    INSERT INTO ${table} (${columnNames.join(", ")})`
      );
      lines.push(`    VALUES (${values.join(", ")})`);
      lines.push(`  \`;`);
    }

    lines.push(
      `  console.log("[seed] ✓ Seeded ${rowCount} ${table} rows");`
    );
    lines.push(``);
  }

  lines.push(`  console.log("[seed] ✅ Seed data insertion complete!");`);
  lines.push(`  await sql.end();`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`seed().catch((err) => {`);
  lines.push(`  console.error("[seed] Failed:", err);`);
  lines.push(`  process.exit(1);`);
  lines.push(`});`);
  lines.push(``);

  return lines.join("\n");
}
