/**
 * Deployment Generator
 * Takes entities and API routes info and produces deploy-ready configurations:
 * - Dockerfile (backend, multi-stage Bun)
 * - Dockerfile.frontend (Vite/React → nginx)
 * - docker-compose.prod.yml (orchestrates backend, frontend, PostgreSQL)
 * - fly.toml (Fly.io deployment config)
 * - .github/workflows/deploy.yml (GitHub Actions CI/CD)
 * - deploy.sh (build, migrate, deploy shell script)
 */

import type { GeneratedEntity, GeneratedEndpoint } from "./generate";

// ── Types ──────────────────────────────────────────────────────────────────

export interface DeploymentProject {
  dockerfile: string;
  dockerfileFrontend: string;
  dockerComposeProd: string;
  flyToml: string;
  githubActions: string;
  deployScript: string;
}

// ── Helpers ─────────────────────────────────────────────────────────────────

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function pluralizeEntity(name: string): string {
  if (/s$/.test(name) || /x$/.test(name) || /z$/.test(name) || /ch$/.test(name) || /sh$/.test(name)) {
    return name + "es";
  }
  if (/[^aeiou]y$/i.test(name)) {
    return name.slice(0, -1) + "ies";
  }
  return name + "s";
}

// ── Template Generators ─────────────────────────────────────────────────────

function generateDockerfile(domainSlug: string, entities: GeneratedEntity[]): string {
  const entityNames = entities.map(e => e.name).join(", ");
  return `# ────────────────────────────────────────────────────────────────────────────
# Backend Dockerfile — ${entityNames} API
# Multi-stage build for Bun + Hono
# Generated by Genesis Platform ASGP Engine
# ────────────────────────────────────────────────────────────────────────────

# ── Builder Stage ──────────────────────────────────────────────────────────
FROM oven/bun:1 AS builder

WORKDIR /app

# Install dependencies (layer caching)
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# Copy source
COPY tsconfig.json ./
COPY src/ ./src/

# Type-check and build (optional — Bun can run TS natively, but we verify)
RUN bun run --if-present build || echo "No build step defined; running TS directly."

# ── Production Stage ───────────────────────────────────────────────────────
FROM oven/bun:1-slim AS production

WORKDIR /app

# Copy only what's needed
COPY --from=builder /app/package.json /app/bun.lock ./
COPY --from=builder /app/tsconfig.json ./
COPY --from=builder /app/src/ ./src/

# Install production-only dependencies
RUN bun install --frozen-lockfile --production

# Create a non-root user
RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser
USER appuser

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD curl -f http://localhost:3001/api/health || exit 1

EXPOSE 3001

ENV NODE_ENV=production
ENV PORT=3001

CMD ["bun", "run", "src/index.ts"]`;
}

function generateDockerfileFrontend(domainSlug: string, entities: GeneratedEntity[]): string {
  const entityNames = entities.map(e => e.name).join(", ");
  return `# ────────────────────────────────────────────────────────────────────────────
# Frontend Dockerfile — ${entityNames} UI
# Multi-stage: Vite build → nginx serve
# Generated by Genesis Platform ASGP Engine
# ────────────────────────────────────────────────────────────────────────────

# ── Builder Stage ──────────────────────────────────────────────────────────
FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json* bun.lock* ./

# Detect package manager
RUN if [ -f bun.lock ]; then \\
      npm install -g bun && bun install; \\
    elif [ -f package-lock.json ]; then \\
      npm ci; \\
    else \\
      npm install; \\
    fi

COPY . .

# Build the Vite/React app
RUN npm run build

# ── Production Stage ───────────────────────────────────────────────────────
FROM nginx:1.27-alpine AS production

# Remove default nginx config
RUN rm -rf /usr/share/nginx/html/*

# Copy built files from builder
COPY --from=builder /app/dist /usr/share/nginx/html

# Custom nginx config: SPA routing + gzip + security headers
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD wget -qO- http://localhost:80/ || exit 1

CMD ["nginx", "-g", "daemon off;"]`;
}

function generateDockerComposeProd(domainSlug: string, entities: GeneratedEntity[]): string {
  const appName = domainSlug || "app";
  return `# ────────────────────────────────────────────────────────────────────────────
# Docker Compose — Production Deployment
# ${entities.map(e => e.name).join(", ")} Domain
# Generated by Genesis Platform ASGP Engine
# ────────────────────────────────────────────────────────────────────────────

version: "3.9"

services:
  # ── PostgreSQL ──────────────────────────────────────────────────────────
  postgres:
    image: postgres:16-alpine
    container_name: ${appName}-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: \${DB_USER:-app_user}
      POSTGRES_PASSWORD: \${DB_PASSWORD:-change_me_in_production}
      POSTGRES_DB: \${DB_NAME:-${appName}_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${DB_USER:-app_user} -d \${DB_NAME:-${appName}_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - app-network

  # ── Backend API ─────────────────────────────────────────────────────────
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${appName}-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: "3001"
      DATABASE_URL: postgres://\${DB_USER:-app_user}:\${DB_PASSWORD:-change_me_in_production}@postgres:5432/\${DB_NAME:-${appName}_db}
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - app-network

  # ── Frontend ────────────────────────────────────────────────────────────
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: ${appName}-web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge`;
}

function generateFlyToml(domainSlug: string, entities: GeneratedEntity[]): string {
  const appName = `genesis-${domainSlug}-api`;
  return `# ────────────────────────────────────────────────────────────────────────────
# Fly.io — Backend Deployment Configuration
# ${entities.map(e => e.name).join(", ")} API
# Generated by Genesis Platform ASGP Engine
# ────────────────────────────────────────────────────────────────────────────

app = "${appName}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/api/health"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1`;
}

function generateGitHubActions(domainSlug: string, entities: GeneratedEntity[]): string {
  const entityNames = entities.map(e => e.name).join(", ");
  return `# ────────────────────────────────────────────────────────────────────────────
# GitHub Actions — CI/CD Pipeline
# ${entityNames} Domain
# Generated by Genesis Platform ASGP Engine
# ────────────────────────────────────────────────────────────────────────────

name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FLY_API_TOKEN: \${{ secrets.FLY_API_TOKEN }}

jobs:
  # ── Type Check & Lint ───────────────────────────────────────────────────
  check:
    name: Type Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type-check
        run: bun run typecheck --if-present || echo "No typecheck script"

  # ── Run Tests ───────────────────────────────────────────────────────────
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: check
    defaults:
      run:
        working-directory: ./backend

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run migrations
        run: bun run db:migrate --if-present || echo "No migration script"
        env:
          DATABASE_URL: postgres://test_user:test_pass@localhost:5432/test_db

      - name: Run tests
        run: bun test --if-present || echo "No tests defined"

  # ── Build & Push Docker Images ──────────────────────────────────────────
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta — backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/\${{ github.repository }}/backend
          tags: |
            type=sha,format=long
            type=ref,event=branch

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: \${{ steps.meta-backend.outputs.tags }}
          labels: \${{ steps.meta-backend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker meta — frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/\${{ github.repository }}/frontend
          tags: |
            type=sha,format=long
            type=ref,event=branch

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.frontend
          push: true
          tags: \${{ steps.meta-frontend.outputs.tags }}
          labels: \${{ steps.meta-frontend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ── Deploy to Fly.io ────────────────────────────────────────────────────
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy backend
        working-directory: ./backend
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: \${{ secrets.FLY_API_TOKEN }}
`;
}

function generateDeployScript(domainSlug: string, entities: GeneratedEntity[]): string {
  const entityNames = entities.map(e => e.name).join(", ");
  return `#!/usr/bin/env bash
# ────────────────────────────────────────────────────────────────────────────
# deploy.sh — Build, migrate, and deploy the ${entityNames} application
# Generated by Genesis Platform ASGP Engine
# ────────────────────────────────────────────────────────────────────────────

set -euo pipefail

APP_NAME="${domainSlug || "app"}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Colors ─────────────────────────────────────────────────────────────────
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
RED='\\033[0;31m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

log()  { echo -e "\\${GREEN}[✓]\\${NC} \$1"; }
warn() { echo -e "\\${YELLOW}[!]\\${NC} \$1"; }
err()  { echo -e "\\${RED}[✗]\\${NC} \$1"; }
info() { echo -e "\\${BLUE}[i]\\${NC} \$1"; }

# ── Prerequisites check ────────────────────────────────────────────────────
check_prereqs() {
  info "Checking prerequisites..."

  command -v docker >/dev/null 2>&1 || { err "Docker is required but not installed."; exit 1; }
  log "Docker is installed"

  command -v docker compose >/dev/null 2>&1 || command -v docker-compose >/dev/null 2>&1 || {
    err "Docker Compose is required but not installed."
    exit 1
  }
  log "Docker Compose is installed"

  command -v bun >/dev/null 2>&1 || { warn "Bun is not installed — using Node.js fallback."; }
}

# ── Environment Setup ──────────────────────────────────────────────────────
setup_env() {
  info "Setting up environment..."

  if [ ! -f backend/.env ]; then
    if [ -f backend/.env.example ]; then
      cp backend/.env.example backend/.env
      warn "Created backend/.env from .env.example — review and update secrets!"
    else
      cat > backend/.env << 'EOF'
# Database
DATABASE_URL=postgres://app_user:change_me_in_production@localhost:5432/${APP_NAME}_db

# Server
PORT=3001
NODE_ENV=production

# Security — CHANGE THESE!
JWT_SECRET=change-me-to-a-random-string
EOF
      warn "Generated backend/.env with defaults — UPDATE SECRETS before deploying!"
    fi
  fi
  log "Environment files ready"
}

# ── Build Docker Images ────────────────────────────────────────────────────
build_images() {
  info "Building Docker images..."

  info "  → Building backend image..."
  docker build -t "${APP_NAME}-api:latest" ./backend

  info "  → Building frontend image..."
  docker build -t "${APP_NAME}-web:latest" -f ./frontend/Dockerfile.frontend ./frontend

  log "Docker images built successfully"
}

# ── Run Database Migrations ────────────────────────────────────────────────
run_migrations() {
  info "Running database migrations..."

  # Start PostgreSQL if not running
  if ! docker compose -f docker-compose.prod.yml ps postgres 2>/dev/null | grep -q "Up"; then
    info "  → Starting PostgreSQL..."
    docker compose -f docker-compose.prod.yml up -d postgres
    # Wait for PostgreSQL to be healthy
    info "  → Waiting for PostgreSQL to be ready..."
    until docker compose -f docker-compose.prod.yml exec -T postgres pg_isready -U app_user 2>/dev/null; do
      sleep 2
    done
    log "PostgreSQL is ready"
  fi

  # Run migration script if it exists
  if [ -f backend/src/migrate.ts ]; then
    info "  → Running migration script..."
    cd backend && bun run src/migrate.ts || node -e "
      const { Pool } = require('pg');
      const pool = new Pool({ connectionString: process.env.DATABASE_URL });
      console.log('[migrate] Connected to database');
    "
    cd "$SCRIPT_DIR"
    log "Migrations complete"
  else
    warn "No migration script found — skipping"
  fi
}

# ── Start Services ─────────────────────────────────────────────────────────
start_services() {
  info "Starting all services..."
  docker compose -f docker-compose.prod.yml up -d
  log "Services started"

  echo ""
  log "Deployment complete! Services:"
  echo "  • Frontend:  http://localhost"
  echo "  • Backend:   http://localhost:3001"
  echo "  • Health:    http://localhost:3001/api/health"
  echo ""
}

# ── Stop Services ──────────────────────────────────────────────────────────
stop_services() {
  info "Stopping all services..."
  docker compose -f docker-compose.prod.yml down
  log "Services stopped"
}

# ── Usage ──────────────────────────────────────────────────────────────────
usage() {
  echo "Usage: \$0 [command]"
  echo ""
  echo "Commands:"
  echo "  deploy    Build images, run migrations, and start all services (default)"
  echo "  build     Build Docker images only"
  echo "  start     Start services (without rebuilding)"
  echo "  stop      Stop all services"
  echo "  migrate   Run database migrations only"
  echo "  status    Show service status"
  echo "  logs      Show logs from all services"
  echo ""
}

# ── Main ───────────────────────────────────────────────────────────────────
main() {
  local cmd="\${1:-deploy}"

  case "\$cmd" in
    deploy)
      check_prereqs
      setup_env
      build_images
      run_migrations
      start_services
      ;;
    build)
      check_prereqs
      build_images
      ;;
    start)
      start_services
      ;;
    stop)
      stop_services
      ;;
    migrate)
      check_prereqs
      run_migrations
      ;;
    status)
      docker compose -f docker-compose.prod.yml ps
      ;;
    logs)
      docker compose -f docker-compose.prod.yml logs -f --tail=100
      ;;
    -h|--help|help)
      usage
      ;;
    *)
      err "Unknown command: \$cmd"
      usage
      exit 1
      ;;
  esac
}

main "\$@"`;
}

// ── Main Generator ──────────────────────────────────────────────────────────

export function generateDeployment(
  entities: GeneratedEntity[],
  _apiRoutes: string,
  domainSlug?: string
): DeploymentProject {
  const slug = domainSlug || slugify(entities.map(e => e.name).join("-") || "generated-app");

  const safeEntities = entities.length > 0
    ? entities
    : [{
        name: "Record",
        fields: [
          { name: "id", type: "UUID", required: true },
          { name: "name", type: "string", required: true },
          { name: "createdAt", type: "datetime", required: true },
        ],
      }];

  return {
    dockerfile: generateDockerfile(slug, safeEntities),
    dockerfileFrontend: generateDockerfileFrontend(slug, safeEntities),
    dockerComposeProd: generateDockerComposeProd(slug, safeEntities),
    flyToml: generateFlyToml(slug, safeEntities),
    githubActions: generateGitHubActions(slug, safeEntities),
    deployScript: generateDeployScript(slug, safeEntities),
  };
}
