/**
 * ZIP Generator
 * Takes a GenerationResult and produces a downloadable ZIP file
 * containing the complete project directory structure.
 *
 * Uses JSZip for in-memory ZIP creation — no filesystem writes needed.
 */

import JSZip from "jszip";
import type { GenerationResult } from "./generate";

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/**
 * Generate a ZIP archive containing all project files.
 * Returns the ZIP as a base64-encoded string (suitable for TanStack server functions).
 */
export async function generateProjectZip(
  result: GenerationResult
): Promise<string> {
  const zip = new JSZip();
  const domainSlug = slugify(result.domain || "generated-app");
  const projectRoot = `${domainSlug}-project`;

  // ── Root README.md ─────────────────────────────────────────────────────
  const rootReadme = buildRootReadme(result);
  zip.file(`${projectRoot}/README.md`, rootReadme);

  // ── Backend ────────────────────────────────────────────────────────────
  if (result.backendProject) {
    const bp = result.backendProject;
    const bRoot = `${projectRoot}/backend`;
    zip.file(`${bRoot}/package.json`, bp.packageJson);
    zip.file(`${bRoot}/tsconfig.json`, bp.tsconfigJson);
    zip.file(`${bRoot}/.env.example`, bp.envExample);
    zip.file(`${bRoot}/README.md`, bp.readme);
    zip.file(`${bRoot}/src/index.ts`, bp.indexTs);
    zip.file(`${bRoot}/src/config.ts`, bp.configTs);
    for (const mw of bp.middleware) {
      zip.file(`${bRoot}/src/middleware/${mw.filename}`, mw.content);
    }
    // Also include the generated API routes as routes.ts
    if (result.apiRoutes) {
      zip.file(`${bRoot}/src/routes.ts`, result.apiRoutes);
    }
  }

  // ── Database ───────────────────────────────────────────────────────────
  if (result.databaseProject) {
    const dp = result.databaseProject;
    const dRoot = `${projectRoot}/database`;
    zip.file(`${dRoot}/docker-compose.yml`, dp.dockerCompose);
    zip.file(`${dRoot}/.env.example`, dp.envExample);
    for (const mig of dp.migrations) {
      zip.file(`${dRoot}/migrations/${mig.filename}`, mig.content);
    }
    zip.file(`${dRoot}/src/connection.ts`, dp.connectionCode);
    zip.file(`${dRoot}/src/migrate.ts`, dp.migrateCode);
    zip.file(`${dRoot}/src/seed.ts`, dp.seedCode);
  }

  // ── Frontend ───────────────────────────────────────────────────────────
  if (result.frontendProject) {
    const fp = result.frontendProject;
    const fRoot = `${projectRoot}/frontend`;
    zip.file(`${fRoot}/package.json`, fp.files.find(f => f.filename === "package.json")?.content || "");
    zip.file(`${fRoot}/tsconfig.json`, fp.files.find(f => f.filename === "tsconfig.json")?.content || "");
    zip.file(`${fRoot}/tsconfig.node.json`, fp.files.find(f => f.filename === "tsconfig.node.json")?.content || "");
    zip.file(`${fRoot}/vite.config.ts`, fp.files.find(f => f.filename === "vite.config.ts")?.content || "");
    zip.file(`${fRoot}/tailwind.config.js`, fp.files.find(f => f.filename === "tailwind.config.js")?.content || "");
    zip.file(`${fRoot}/postcss.config.js`, fp.files.find(f => f.filename === "postcss.config.js")?.content || "");
    zip.file(`${fRoot}/index.html`, fp.indexHtml);
    zip.file(`${fRoot}/src/index.tsx`, fp.indexTsx);
    zip.file(`${fRoot}/src/App.tsx`, fp.appTsx);
    zip.file(`${fRoot}/src/types.ts`, fp.files.find(f => f.filename === "src/types.ts")?.content || "");
    zip.file(`${fRoot}/src/index.css`, fp.files.find(f => f.filename === "src/index.css")?.content || "");
    // Component files
    for (const file of fp.files) {
      if (file.filename.startsWith("src/components/")) {
        zip.file(`${fRoot}/${file.filename}`, file.content);
      }
    }
    // Frontend README
    zip.file(`${fRoot}/README.md`, buildFrontendReadme(result));
  }

  // ── Dashboard ───────────────────────────────────────────────────────────
  if (result.dashboardProject) {
    const dRoot = `${projectRoot}/dashboard`;
    zip.file(`${dRoot}/Dashboard.tsx`, result.dashboardProject.dashboardTsx);
    zip.file(`${dRoot}/README.md`, buildDashboardReadme(result));
  }

  // ── Also include SQL schema at root level for convenience ──────────────
  if (result.sql) {
    zip.file(`${projectRoot}/database/schema.sql`, result.sql);
  }

  // Generate and return as base64
  const buffer = await zip.generateAsync({ type: "nodebuffer" });
  return Buffer.from(buffer).toString("base64");
}

// ── README builders ───────────────────────────────────────────────────────

function buildRootReadme(result: GenerationResult): string {
  const lines: string[] = [];
  lines.push(`# ${result.domain} — Generated by Genesis Platform`);
  lines.push("");
  lines.push(result.summary);
  lines.push("");
  lines.push("## Project Structure");
  lines.push("");
  lines.push("```");
  lines.push("├── backend/          # Bun + Hono API server");
  lines.push("│   ├── src/");
  lines.push("│   │   ├── index.ts        # Server entry point");
  lines.push("│   │   ├── config.ts       # Environment configuration");
  lines.push("│   │   ├── routes.ts       # API route handlers");
  lines.push("│   │   └── middleware/     # Auth, logging, error handling");
  lines.push("│   ├── package.json");
  lines.push("│   ├── tsconfig.json");
  lines.push("│   └── .env.example");
  lines.push("├── database/         # PostgreSQL schema & tooling");
  lines.push("│   ├── docker-compose.yml  # Local PostgreSQL instance");
  lines.push("│   ├── schema.sql          # Complete DDL");
  lines.push("│   ├── migrations/         # Incremental migrations");
  lines.push("│   └── src/                # Connection, migration runner, seed data");
  lines.push("└── frontend/         # React + TypeScript + Tailwind");
  lines.push("    ├── src/");
  lines.push("    │   ├── index.tsx       # React entry point");
  lines.push("    │   ├── App.tsx         # Root component");
  lines.push("    │   ├── types.ts        # TypeScript types");
  lines.push("    │   ├── index.css       # Tailwind + base styles");
  lines.push("    │   └── components/     # All generated components");
  lines.push("    ├── index.html");
  lines.push("    ├── package.json");
  lines.push("    ├── vite.config.ts");
  lines.push("    └── tailwind.config.js");
  if (result.dashboardProject) {
    lines.push("├── dashboard/        # Admin Dashboard");
    lines.push("│   ├── Dashboard.tsx       # Recharts dashboard with KPIs & charts");
    lines.push("│   └── README.md");
  }
  lines.push("```");
  lines.push("");
  lines.push("## Getting Started");
  lines.push("");
  lines.push("### 1. Start the database");
  lines.push("```bash");
  lines.push("cd database");
  lines.push("docker-compose up -d");
  lines.push("bun run src/migrate.ts");
  lines.push("bun run src/seed.ts");
  lines.push("```");
  lines.push("");
  lines.push("### 2. Start the backend");
  lines.push("```bash");
  lines.push("cd backend");
  lines.push("cp .env.example .env");
  lines.push("bun install");
  lines.push("bun run dev");
  lines.push("```");
  lines.push("");
  lines.push("### 3. Start the frontend");
  lines.push("```bash");
  lines.push("cd frontend");
  lines.push("bun install");
  lines.push("bun run dev");
  lines.push("```");
  lines.push("");
  lines.push("## Data Model");
  lines.push("");
  for (const entity of result.entities) {
    lines.push(`### ${entity.name}`);
    lines.push("");
    lines.push("| Field | Type | Required | Description |");
    lines.push("|-------|------|----------|-------------|");
    for (const field of entity.fields) {
      lines.push(
        `| ${field.name} | \`${field.type}\` | ${field.required ? "✓" : ""} | ${field.description || ""} |`
      );
    }
    lines.push("");
  }
  lines.push("## API Endpoints");
  lines.push("");
  lines.push("| Method | Path | Description |");
  lines.push("|--------|------|-------------|");
  for (const ep of result.endpoints) {
    lines.push(`| ${ep.method} | \`${ep.path}\` | ${ep.description} |`);
  }
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("*Generated by [Genesis Platform](https://genesis-platform.com) — Autonomous Software Generation*");

  return lines.join("\n");
}

function buildFrontendReadme(result: GenerationResult): string {
  const lines: string[] = [];
  lines.push("# Frontend — React + TypeScript + Tailwind");
  lines.push("");
  lines.push("This frontend was generated by Genesis Platform based on your business requirements.");
  lines.push("");
  lines.push("## Tech Stack");
  lines.push("");
  lines.push("- **React 19** with TypeScript");
  lines.push("- **Vite** for development and bundling");
  lines.push("- **Tailwind CSS** for styling");
  lines.push("");
  lines.push("## Components");
  lines.push("");
  for (const comp of result.components) {
    lines.push(`- **${comp.name}** (${comp.type}) — ${comp.description}`);
  }
  lines.push("");
  lines.push("## Getting Started");
  lines.push("");
  lines.push("```bash");
  lines.push("bun install");
  lines.push("bun run dev");
  lines.push("```");
  lines.push("");
  lines.push("The dev server runs at http://localhost:5173");
  return lines.join("\n");
}

function buildDashboardReadme(result: GenerationResult): string {
  const lines: string[] = [];
  const summary = result.dashboardProject?.summary;
  lines.push("# Dashboard — Admin Analytics Dashboard");
  lines.push("");
  lines.push("This admin dashboard was generated by Genesis Platform based on your business requirements.");
  lines.push("");
  lines.push("## Features");
  lines.push("");
  if (summary) {
    lines.push(`- **${summary.kpiCount} KPI cards** — Auto-generated metrics based on entity types`);
    lines.push(`- **${summary.chartCount} charts** — Bar chart, line chart, and donut chart using Recharts`);
  }
  lines.push("- **Recent Activity table** — Latest records from the primary entity");
  lines.push("- **Quick Actions** — Common operations (Add New, Export, Generate Report, Search)");
  lines.push("");
  lines.push("## Tech Stack");
  lines.push("");
  lines.push("- **React** with TypeScript");
  lines.push("- **Recharts** for data visualization");
  lines.push("- **Tailwind CSS** (dark theme)");
  lines.push("");
  lines.push("## Usage");
  lines.push("");
  lines.push("Copy `Dashboard.tsx` into your frontend project's `src/components/` directory.");
  lines.push("");
  lines.push("Make sure your project has `recharts` installed:");
  lines.push("");
  lines.push("```bash");
  lines.push("npm install recharts");
  lines.push("```");
  lines.push("");
  lines.push("Then import and use the component:");
  lines.push("");
  lines.push("```tsx");
  lines.push("import Dashboard from './components/Dashboard';");
  lines.push("```");
  lines.push("");
  lines.push("## Data Integration");
  lines.push("");
  lines.push("The dashboard uses mock data by default. To connect real data:");
  lines.push("1. Replace mock data arrays with API calls to your backend");
  lines.push("2. Wire up KPI values to real database queries");
  lines.push("3. Update chart data from your analytics endpoints");
  lines.push("");
  lines.push("*Generated by [Genesis Platform](https://genesis-platform.com) — Autonomous Software Generation*");
  return lines.join("\n");
}
